[pytest]
markers =
    test_lkz_lkp: Сквозной сценарий ЛКЗ → ЛКП
    test_lkz_lke_lkp: Сквозной сценарий ЛКЗ → ЛКЭ → ЛКП
    smoke: тесты с высоким приоритетом, основные сценарии
    regression: тесты для регрессионного тестирования
    feature: указывает функциональную область теста
    story: указывает историю/сценарий использования
    allure: метки из библиотеки allure для категоризации и описания тестов
    order: задаёт порядок выполнения тестов (используется с pytest-ordering)

addopts = -n 1  # Запускать тесты последовательно, по одному

